### ISSUE TITLE
Rebase PyTDF on current ROOT master

### ISSUE THREAD

**Issue by eguiraud** [shravan97/PyTDF#12]
In particular switch from `TDataFrame` to `RDataFrame`.
@etejedor @diocas @dpiparo what should the rebased version be called? `PyRDF`?

**Comment by etejedor** [comment]
Is `PyDF` too disruptive? Otherwise `PyRDF`is good.

**Comment by shravan97** [comment]
Shall we go with PyRDF itself ?
