### ISSUE TITLE
Make a new proposal for the unit tests of Operation

### ISSUE THREAD

**Issue by etejedor** [shravan97/PyTDF#13]
In particular the DFS part and the pruning.

**Comment by shravan97** [comment]
@etejedor , from what we discussed on Thrusday, I guess you'd asked me to make a proposal for `OperationReadTest` in `test_node.py`. I've now changed this class to : 

```python
class OperationReadTest(unittest.TestCase):
    def test_attr_read(self):       
        node = Node(None, None)
        func = node.Define
        self.assertEqual(node._cur_attr, "Define")

    def test_operation(self):
        node = Node(None, None)
        newNode = node.Define(1, "b", a="1", b=2)
        self.assertEqual(newNode.operation.name, "Define")
        self.assertEqual(newNode.operation.args, (1, "b"))
        self.assertEqual(newNode.operation.kwargs, {"a":"1", "b":2})
```
My explanation for this now is that, I'm checking how the `Node` class is intercepting the user's desired operation name in `test_attr_read()` function. And I'm checking how `Node` class is setting the required operation in `test_operation()` function. In a nutshell, this particular test is to check how the `Node` class is properly taking in the required operation parameters and setting up an `Operation` object

**Comment by etejedor** [comment]
@shravan97 this looks good, but there was also some part related to the pruning, which you also tested in some other test. Let's move the discussion to the PR.
